# Generated by Django 4.1 on 2022-09-05 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0002_subject_register"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subject",
            name="subject_id",
            field=models.CharField(max_length=5),
        ),
    ]
