# Generated by Django 4.1.1 on 2022-09-10 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("regist", "0003_remove_student_subjects_register"),
    ]

    operations = [
        migrations.RenameField(
            model_name="register",
            old_name="student_id",
            new_name="student",
        ),
        migrations.RenameField(
            model_name="register",
            old_name="subject_id",
            new_name="subject",
        ),
    ]
