# Generated by Django 4.1.1 on 2022-09-10 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=5)),
                ("name", models.CharField(max_length=50)),
                ("semester", models.IntegerField()),
                ("year", models.IntegerField()),
                ("max_cap", models.IntegerField()),
                ("status", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=50)),
                ("first", models.CharField(max_length=50)),
                ("last", models.CharField(max_length=50)),
                (
                    "subject",
                    models.ManyToManyField(
                        blank=True, related_name="students", to="regist.subject"
                    ),
                ),
            ],
        ),
    ]
