# Generated by Django 4.1 on 2022-09-05 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject_id", models.IntegerField()),
                ("subject_name", models.CharField(max_length=50)),
                ("semester", models.IntegerField()),
                ("year", models.IntegerField()),
                ("max_cap", models.IntegerField()),
                ("status", models.BooleanField()),
            ],
        ),
    ]
