# Generated by Django 4.1 on 2022-09-05 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("subject", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Subject",
        ),
    ]
